### ISSUE TITLE
Refreshing statusline after closing CtrlP window

### ISSUE THREAD

**Issue by tap349** [itchyny/lightline.vim#222] opened 2017-03-31 00:19 UTC
I had similar problem with vim-airline as well:

- open vim and any file
- open CtrlP window and close it without selecting any file (by pressing Escape)

statusline of the first and only window with opened file remains grayish - that is lightline is disabled. after any action (switching to another window and back, moving cursor, etc.) lightline is enabled again.
that is I need to call `lightline#update()` after closing CtrlP window. the problem is I don't know when to call it in my vimrc - I experimented with calling it for almost all events without any success.

maybe you can suggest some solution - I'm out of ideas (

**Comment by itchyny** [comment] 2017-03-31 00:36
The problem is that CtrlP uses `noautocmd` on closing its window [ref](https://github.com/ctrlpvim/ctrlp.vim/blob/754ed390624513de46a2b7159ef9c73a26eedf56/autoload/ctrlp.vim#L940). Other plugin cannot detect when CtrlP closes the window unless it stops using `noautocmd`.

**Comment by tap349** [comment] 2017-04-02 08:16
@itchyny thank you for your response. if this is the only way to update statusline I'll try to ask CtlrP maintainer if he can anything about it (maybe trigger some user event).

**Comment by dayancn** [comment] 2017-04-18 08:53
Hi, relativepath doesn't work when use ctrl + ] to jump to another file.

**Comment by itchyny** [comment] 2017-04-18 10:33
@dayancn Are you saying your problem is related to this issue?

**Comment by dayancn** [comment] 2017-04-19 01:19
sorry. no, I will create a new issue.

**Closed** 2017-04-30 12:49 UTC
Labels: configuration

**Comment by todashuta** [comment] 2022-01-09 06:31
If you have a newer version of Vim that supports `timer_start()`,
you can use the following code to update the lightline after closing the CtrlP buffer.

```vim
let g:ctrlp_buffer_func = {
      \   'exit': 'CtrlPBufferFunc_exit',
      \ }
function! CtrlPBufferFunc_exit()
  call timer_start(0, { -> lightline#update() })
endfunction
```
