### ISSUE TITLE
disappearing colors

### ISSUE THREAD

**Issue by nhooyr** [itchyny/lightline.vim#144] opened 2016-01-21 05:48 UTC
In neovim terminals this happens sometimes only in 'terminal' or 'insert' mode.

<img width="1440" alt="screen shot 2016-01-21 at 12 46 34 am" src="https://cloud.githubusercontent.com/assets/10180857/12472655/9255b1be-bfd8-11e5-9358-63496320db0d.png">

Here it is in the same buffer but in normal mode. 

<img width="1440" alt="screen shot 2016-01-21 at 12 46 39 am" src="https://cloud.githubusercontent.com/assets/10180857/12472660/a146c4f6-bfd8-11e5-84ff-3adf31ba4dc4.png">

No clue what's wrong.

**Comment by itchyny** [comment] 2016-01-21 06:17
I cannot reproduce the bug with the following step.
Save the following file as `.nvimrc.test`
```vim
set nocompatible
filetype off
set rtp+=/path/to/lightline.vim
filetype plugin indent on
set laststatus=2
```
Open neovim with `nvim -u .nvimrc.test`
Go to insert mode or execute `:terminal`.

**Comment by nhooyr** [comment] 2016-01-21 06:19
I'll try figuring out how to reproduce it. I'm not sure right now.

**Comment by nhooyr** [comment] 2016-01-22 10:21
@itchyny figured it out. It has to do with sourcing vimrc again. 

https://www.youtube.com/watch?v=y2H0-5H7JVo&feature=youtu.be

I also tested with default vim-airline and it doesn't seem to affect them.

**Comment by itchyny** [comment] 2016-01-22 11:44
Please paste the **minimal** vimrc (which is under 20 lines at most) to reproduce the bug. Otherwise I cannot investigate the reason what causes the bug or even I do not know this is a bug of lightline or of other plugin or of Vim itself.

**Comment by nhooyr** [comment] 2016-01-22 11:45
@itchyny were you able to watch the video?

I'll post a vimrc soon just give me a few.

**Comment by itchyny** [comment] 2016-01-23 17:06
Yes but I found no clue to reproduce. I close this issue because the issue report is less informative.

**Comment by nhooyr** [comment] 2016-01-23 17:06
@itchyny sorry I didn't post the vimrc but did you watch the video?

**Closed** 2016-01-23 17:06 UTC

**Comment by itchyny** [comment] 2016-01-23 17:54
Yes

**Comment by nhooyr** [comment] 2016-01-23 18:20
```vim
filetype off
set rtp+=/usr/local/etc/dotfiles/nvim/plugged/lightline.vim
set rtp+=/usr/local/etc/dotfiles/nvim/plugged/Apprentice
filetype plugin indent on
set laststatus=2
colorscheme apprentice
```
It only happens if a colorscheme is set (I tried apprentice and solarized etc. 

Steps to reproduce

1. Open neovim with the above as init.vim or use the -u option
2. Open a terminal with ':term'
3. Now type <c-\><c-n> to leave terminal mode and then source the init.vim file with ':source pathtoinit.vim'
4. Now reenter terminal mode by pressing 'i'. Bam the colours should disappear.

**Comment by itchyny** [comment] 2016-01-24 01:03
I still cannot reproduce because I don't see what `init.vim` is.

**Comment by nhooyr** [comment] 2016-01-24 01:04
@itchyny in neovim, the vimrc is called init.vim and its under $XDG_CONFIG_HOME/nvim/init.vim. This is a neovim problem.

**Comment by itchyny** [comment] 2016-01-24 01:18
I still cannot reproduce with the following steps.
```
 $ cat > ./vimrc
filetype off
set rtp+=/path/to/lightline.vim
set rtp+=/path/to/Apprentice
filetype plugin indent on
set laststatus=2
colorscheme apprentice
^D
 $ nvim -u ./vimrc<CR>
:terminal<CR>
^D<CR>
:so ./vimrc<CR>
:terminal<CR>
```
Am I doing incorrectly?

**Comment by itchyny** [comment] 2016-01-24 01:19
Ah, OK. It seems to be appeared on my environment.

**Comment by nhooyr** [comment] 2016-01-24 01:20
great. hopefully you can figure out whats going on.

**Comment by nhooyr** [comment] 2016-01-28 19:56
@itchyny forgot to reopen the issue, its still closed even though you could reproduce it.

**Comment by nhooyr** [comment] 2016-02-09 04:35
@itchyny any updates on this? its still closed even though you managed to reproduce.

**Comment by itchyny** [comment] 2016-02-09 04:47
I don't want be bothered by the behaviour which occurs only in neovim, the editor which has different architecture of rendering compared to Vim.

**Comment by nhooyr** [comment] 2016-02-09 05:06
@itchyny in that case i'll take a stab and see if I can fix it.

**Comment by nhooyr** [comment] 2016-02-09 23:23
@itchyny it has to do with running `hi clear` in the colorscheme file. This resets the highlighting groups. For some reason lightline then doesn't then reset the terminal highlight groups. Do you know exactly how to fix this?

**Comment by nhooyr** [comment] 2016-02-09 23:29
I fixed it, i'll create a PR

**Comment by Billy-** [comment] 2019-03-21 11:00
I'm having this issue on Vim 8 on OSX. Is it related? I saw that the PR changed a block that was in `has('win32')`, so could this fix be applied for osx, too?

**Comment by itchyny** [comment] 2019-03-26 09:15
@Billy- Please create **a new issue** if there's some trouble with environment info, precise steps expected behavior and minimal vimrc if possible.

**Comment by Billy-** [comment] 2019-03-26 10:19
I hope I'll be able to find the spare time to do that..
