### ISSUE TITLE
Spurious separator on the right

### ISSUE THREAD

**Issue by jjo93sa** [itchyny/lightline.vim#285] opened 2018-01-26 19:09 UTC
Love lightline, but there's two small issues that are bugging me, both examples can be seen in this screen shot:

<img width="666" alt="screen shot 2018-01-26 at 18 44 54" src="https://user-images.githubusercontent.com/15944915/35455762-0fa06c40-02cb-11e8-9367-0d3fd631133d.png">

1. A spurious separator that's bugging me on the right hand side, which shows as really dark colour, see to the left of "unix";
2. Some of the separators (I'm using solid arrows) seem to be rendered in a slightly different shade than the background of the status area they are rendered in. For example, see the arrow to the right of "NORMAL", the blue colour is slightly different than the blue text background.

This is part of my lightline configuration, arrows aren't showing:

~~~
let g:lightline = {
      \ 'colorscheme': 'solarized',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'fugitive', 'filename', 'ctrlpmark' ] ]
      \ },
      \ 'component': { 
      \   'lineinfo': ' %3l:%-2v',
      \ },
      \ 'component_function': {
      \   'fugitive': 'LightLineFugitive',
      \   'readonly': 'LightLineReadonly',
      \   'modified': 'LightLineModified',
      \   'filename': 'LightLineFilename',
      \   'ctrlpmark': 'CtrlPMark',
      \ },
      \ 'separator': { 'left': '', 'right': '' },
      \ 'subseparator': { 'left': '', 'right': '' }
      \ }
~~~

Please can you tell me what am I doing wrong?

**Comment by itchyny** [comment] 2018-01-27 03:36
What terminal application are you using? Assuming iTerm2,

- Set Profiles>Colors>Minimum contrast to the Lowest.
- Set Profiles>Window>Transparency to the Opaquest.

**Comment by jjo93sa** [comment] 2018-01-27 11:13
Sorry @itchyny I should've mentioned in my issue: I'm using the stock Terminal.app on macOS 10.13.2

**Comment by itchyny** [comment] 2018-01-27 15:00
Are you configuring transparency? The problem is caused by the terminal emulator rendering and cannot be fixed by this plugin anyway.

**Comment by jjo93sa** [comment] 2018-01-31 15:49
Ah, that's solved it; I had some transparency and removing that has
corrected both the colour problem and the spurious separator. Thanks

**Closed** 2018-01-31 15:55 UTC
Labels: question
