### ISSUE TITLE
status line gets corrupted when using gvim command line flag "--remote-tab"

### ISSUE THREAD

**Issue by gombosh** [itchyny/lightline.vim#394] opened 2019-09-26 15:04 UTC
when gvim loads you can see lightline working for a second, and then the name of the tab file overrides the entire status line and only it appears on it.

example with:
gvim -X -f --servername 3 --remote-tab-silent new

![image](https://user-images.githubusercontent.com/10688086/65700270-083e8580-e088-11e9-932e-fe40c5a0761c.png)

**Comment by itchyny** [comment] 2019-10-04 04:03
This is reproducible but I have difficulty in debugging this.

**Comment by gombosh** [comment] 2019-10-04 05:16
Can I help somehow?

**Comment by itchyny** [comment] 2019-10-05 10:27
I can't find where (in the Vim source code) the file is opened and why it does not emit BufEnter.

**Comment by gombosh** [comment] 2019-10-05 12:26
If you will watch closely, you will notice that the status line is being loaded correctly, and only afterwards it gets overwritten.
So that means bufenter is getting called correctly, and the problem happens afterwards.
I found that executing :e<CR> solves it (but it's re-loading the buffer, so I'm not sure it's the best solution).

**Comment by itchyny** [comment] 2019-10-05 13:06
It looks like lightline draws `No Name` so the buffer of `new` file is opened without BufEnter event.

**Comment by itchyny** [comment] 2019-10-05 13:35
Okay, I've got something. The command `tab drop file` removes the lightline statusline.

- With --remote flag, the command returned by `build_drop_cmd` is executed. In the command `tab drop [filename]` is included builded at https://github.com/vim/vim/blob/101e99207f813ca48a4c0787eed9eb8bf67fba5a/src/main.c#L4235-L4237.
- `tab drop [filename]` opens the file without emitting the BufEnter event. This is due to `++autocmd_no_enter`  at https://github.com/vim/vim/blob/0a52df50a0e8fce6f5e0eb5f5373dcd0fa24d83a/src/arglist.c#L1025 in `do_arg_all`, which is called by `ex_all`, `ex_drop` https://github.com/vim/vim/blob/9ca250855b55f4d3292b010525c827dc6992cb61/src/ex_cmds.c#L6530-L6536.

**Comment by itchyny** [comment] 2019-10-05 13:58
Oh, this is already reported at https://github.com/vim/vim/issues/1660. I'm thinking of writing a patch of Vim, this is not a bug of lightline anyway.

**Comment by gombosh** [comment] 2019-10-05 17:57
Can you think of some workaround I can use in my local settings to bypass this issue without the need for a patch?

**Comment by itchyny** [comment] 2020-01-20 13:12
This problem is fixed by Vim 8.2.0116 https://github.com/vim/vim/commit/c10b521628f2b073fa231defa26f23937c91724d.

**Closed by itchyny** 2020-01-20 13:12 UTC
