### ISSUE TITLE
active window has statusline of inactive window

### ISSUE THREAD

**Issue by minusf** [itchyny/lightline.vim#443] opened 2020-04-08 16:17 UTC
i have noticed that once in a blue moon an active window will receive the statusline configured for an inactive one.

is there any way i could debug this somehow?  a `:e` "fixes" it.

**Comment by itchyny** [comment] 2020-04-08 16:29
Please describe the precise steps to reproduce the issue. Also write your Vim version and vimrc.

**Comment by minusf** [comment] 2020-04-08 16:48
yes, if only it was that easy :}   sometimes i notice after hours of coding, so i am afraid i cannot give a step by step reproduction. This very last time, just before submitting this bug report it happened right after `:w` in the only window with a python file.

`NVIM v0.4.3`
vimrc: https://gist.github.com/minusf/f2d482ed3bdbe00cc4fd1c517811e1fc

**Comment by itchyny** [comment] 2020-04-08 16:56
Please paste the entire output of `:au BufWritePre` and `:au BufWritePost`.

**Comment by minusf** [comment] 2020-04-08 17:00
```
:au BufWritePre
--- Autocommands ---

:au BufWritePost
--- Autocommands ---
MyAutoCmd  BufWritePost
    *.py      call Flake8()
    vimrc     so $MYVIMRC
ALEEvents  BufWritePost
    *         call ale#events#SaveEvent(str2nr(expand('<abuf>')))
gzip  BufWritePost
    *.gz      call gzip#write("gzip")
    *.bz2     call gzip#write("bzip2")
    *.Z       call gzip#write("compress -f")
    *.lzma    call gzip#write("lzma -z")
    *.xz      call gzip#write("xz -z")
    *.lz      call gzip#write("lzip")
    *.zst     call gzip#write("zstd --rm")
```

**Comment by itchyny** [comment] 2020-04-08 17:08
This is likely caused by
```vim
  autocmd BufWritePost *.py call Flake8()
```
so change this line to
```vim
  autocmd BufWritePost *.py ++nested call Flake8()
```

**Comment by minusf** [comment] 2020-04-08 17:16
come to think of it, i dont need this actually atm because i use ALE with flake8 anyway, so for now i will comment it out and see what happens.  i will keep `++nested` in mind but tbh i have never seen it recommended with that plugin (or others like it).  it just checks the content and shows a quickfix window if necessary.  but i am out of my depth here, so thank you very much for the tip.

**Comment by jackcogdill** [comment] 2020-04-09 19:25
Same thing is happening to me. I think this [workspace plugin](https://github.com/thaerkh/vim-workspace) might be causing it. The plugin restores saved layout (in my case, about five tabs). When I delete the workspace and load default vim (no tabs), lightline looks fine. Also, when I have the first tab selected, lightline looks fine. It's only when it's restoring a tab with index >1 that lightline looks inactive.

So maybe it has to do with how that plugin is switching tabs?

I can manually fix it like this:
```
:call lightline#update()
:e
:tabn
:tabp
```

**Comment by itchyny** [comment] 2020-04-10 00:44
@jackcogdill I tried installing that plugin but can't reproduce that issue.

**Comment by jackcogdill** [comment] 2020-04-10 05:13
@itchyny  Hm, you're right. I tried doing the same with a fresh vimrc and couldn't repro it. However, it happens without fail with my [vimrc](https://github.com/jackcogdill/dotfiles/blob/master/vim/.vim/vimrc). I have many plugins, so it's hard to tell what's causing it ;--;

**Comment by jackcogdill** [comment] 2020-04-10 05:20
Actually, I commented out all plugins except lightline, gruvbox, and vim-workspace, but the problem persists. It must be something else, or some specific codepath in vim-workspace maybe?

**Comment by itchyny** [comment] 2020-04-10 05:29
I'm closing this issue because the original issue is resolved by the nested attribute. Please create a new issue in different configuration.

**Closed by itchyny** 2020-04-10 05:29 UTC
Labels: configuration
